import { readFileSync } from "node:fs";

const packageJson = JSON.parse(
  readFileSync(new URL("../../package.json", import.meta.url), "utf-8"),
) as { version: string };

export const DEFAULT_BASE_URL = process.env.BBOX_URL ?? "https://mabbox.bytel.fr";
export const DEFAULT_USER_AGENT = `bbox-exporter@${packageJson.version}`;

export const bboxApiRoutes = {
  alerts: "/api/v1/alerts",
  caccess: "/api/v1/parentalcontrol",
  caccessScheduler: "/api/v1/parentalcontrol/scheduler",
  caccessSchedulerRule: "/api/v1/parentalcontrol/scheduler/rule",
  caccessSchedulerRuleById: (id: string | number) => `/api/v1/parentalcontrol/scheduler/rule/${id}`,
  contentFiltering: "/api/v1/contentfiltering",
  deactivation5: "/api/v1/wireless/deactivation",
  device: "/api/v1/device",
  deviceCpu: "/api/v1/device/cpu",
  deviceMemory: "/api/v1/device/mem",
  hostsIdentification: "/api/v1/identification/hosts",
  cpl: "/api/v1/cpl",
  cybersecurity: "/api/v1/cybersecurity",
  dnsStats: "/api/v1/dns/stats",
  deviceOnCAccess: "/api/v1/parentalcontrol/hosts",
  dhcpClients: "/api/v1/dhcp/clients",
  dhcpClientsById: (id: string | number) => `/api/v1/dhcp/clients/${id}`,
  dhcpOptions: "/api/v1/dhcp/options",
  dhcpStatic: "/api/v1/dhcp/clients",
  dhcpv6Options: "/api/v1/dhcp6/options",
  dyndns: "/api/v1/dyndns",
  firewallRules: "/api/v1/firewall/rules",
  guestById: (id: string | number) => `/api/v1/guests/${id}`,
  guestEnable: "/api/v1/wireless/guestenable",
  hosts: "/api/v1/hosts",
  hostsById: (id: string | number) => `/api/v1/hosts/${id}`,
  iptv: "/api/v1/iptv",
  iptvDiags: "/api/v1/iptv/diags",
  lanIP: "/api/v1/lan/ip",
  lanStats: "/api/v1/lan/stats",
  led: "/api/v1/device/led",
  login: "/api/v1/login",
  logout: "/api/v1/logout",
  logs: "/api/v1/device/log",
  me: "/api/v1/hosts/me",
  nat: "/api/v1/nat/rules",
  newihm: "/api/v1/device/newihm",
  notificationAlerts: "/api/v1/notification/alerts",
  reboot: "/api/v1/device/reboot",
  sao: "/api/v1/wan/backup",
  services: "/api/v1/services",
  staticByHosts: (hostId: string | number) => `/api/v1/untouchable/hosts/${hostId}`,
  summary: "/api/v1/summary",
  token: "/api/v1/device/token",
  upnp: "/api/v1/upnp/igd/rules",
  usb: "/api/v1/device/usb",
  usbById: (id: string | number) => `/api/v1/device/usb/${id}`,
  usb3: "/api/v1/device/usb3",
  voip: "/api/v1/voip",
  voipMaskedNumber1: "/api/v1/voip/blockanon/1",
  voipMaskedNumber2: "/api/v1/voip/blockanon/2",
  voipScheduler: "/api/v1/voip/scheduler",
  voipSchedulerRule: "/api/v1/voip/scheduler/rule",
  voipSchedulerRuleById: (id: string | number) => `/api/v1/voip/scheduler/rule/${id}`,
  voipSchedulerNumber: "/api/v1/voip/scheduler/number",
  voipSchedulerNumberById: (id: string | number) => `/api/v1/voip/scheduler/number/${id}`,
  wanIP: "/api/v1/wan/ip",
  wanIPStats: "/api/v1/wan/ip/stats",
  wanFtthStats: "/api/v1/wan/ftth/stats",
  wanDiags: "/api/v1/wan/diags",
  wanXdsl: "/api/v1/wan/xdsl",
  wireless: "/api/v1/wireless",
  wireless24: "/api/v1/wireless/24",
  wireless5: "/api/v1/wireless/5",
  wireless6: "/api/v1/wireless/6",
  wirelessCompatibility: "/api/v1/wireless/compatibility",
  wirelessCompatibilityEnable: "/api/v1/wireless/compatibilityenable",
  wirelessDeactivation5: "/api/v1/wireless/deactivation",
  wirelessGuest: "/api/v1/wireless/guest",
  wirelessGuestEnable: "/api/v1/wireless/guestenable",
  wirelessMlo: "/api/v1/wireless/mlo",
  wirelessRepeater: "/api/v1/wireless/repeater",
  wirelessScheduler: "/api/v1/wireless/scheduler",
  wirelessSchedulerSavedRules: "/api/v1/wireless/scheduler/savedRules",
  wirelessSchedulerRule: "/api/v1/wireless/scheduler/rule",
  wirelessSchedulerRuleById: (id: string | number) => `/api/v1/wireless/scheduler/rule/${id}`,
  wirelessStatsByBand: (band: 24 | 5 | 6) => `/api/v1/wireless/${band}/stats`,
  wirelessSecondary24: "/api/v1/wireless/secondary/24",
  wirelessSecondary5: "/api/v1/wireless/secondary/5",
  wirelessSecondaryEnable: "/api/v1/wireless/secondaryenable",
  wps: "/api/v1/wireless/wps",
  display: "/api/v1/device/display",
  extenderDisplay: "/api/v1/device/extender/display",
  usersave: "/api/v1/usersave",
  passwordRecovery: "/api/v1/password-recovery",
  passwordRecoveryVerify: "/api/v1/password-recovery/verify",
  resetPassword: "/api/v1/reset-password",
  hibernateScheduler: "/api/v1/hibernate/scheduler",
  hibernateSchedulerRule: "/api/v1/hibernate/scheduler/rule",
  hibernateSchedulerRuleById: (id: string | number) => `/api/v1/hibernate/scheduler/rule/${id}`,
} as const;
